#!/bin/sh

echo "::: higgs-ml [prediction]..."
echo "::: args:" $@

in=$1
trained=$2
out=$3

python2 higgsml_simplest_v2.py $in $trained $out || exit 1

echo "::: higgs-ml [prediction]... [ok]"
exit 0
