#!/bin/sh

echo "::: generate team-1..."
hml-mk-zip higgsml-test-team1.zip team-1

echo "::: generate team-2..."
go get github.com/sbinet/go-higgsml
/bin/cp `which go-higgsml` team-2/.
hml-mk-zip higgsml-test-team2.zip team-2
/bin/rm -rf team-2/go-higgsml

echo "::: generate team-3..."
hml-mk-zip higgsml-test-team3.zip team-3/*

echo "::: generate team-4..."
/bin/cp `which go-higgsml` team-4/code-1/.
hml-mk-zip higgsml-test-team4.zip team-4/*
/bin/rm -rf team-4/code-1/go-higgsml
